application: stuxy
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /env/(.*\.(html|css|js|dart))
  static_files: html/\1
  upload: html/(.*\.(html|css|js|dart))

- url: /.*
  script: _go_app
